title: Rajdeep Sarkar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>As a passionate data scientist, I am dedicated to using my skills and expertise to turn complex data into meaningful insights. 
  With a background in mathematics, statistics, and computer science, 
  I am well-versed in a variety of data analysis techniques, including machine learning, deep learning, and natural language processing. 
  Throughout my career, I have worked on a diverse range of projects, from developing predictive models for financial services companies to analyzing social media
  data to better understand customer behavior. 
  In each case, I have leveraged my strong analytical skills to uncover insights that have helped my clients make better decisions.<br>
  
  
  
  
  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/rajdeep-sarkar-478920143/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
