title: Rajdeep Sarkar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>As a passionate data scientist, I am dedicated to using my skills and expertise to turn complex data into meaningful insights. 
  With a background in mathematics, statistics, and computer science, 
  I am well-versed in a variety of data analysis techniques, including machine learning, deep learning, and natural language processing. <br>
  
  
  <br>In addition to my technical skills, I am also an excellent communicator and team player. 
  With a passion for lifelong learning, I am always seeking out new challenges and opportunities to expand my skills and knowledge. <br>
  
  <a href="https://www.linkedin.com/in/rajdeep-sarkar-478920143/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
